### ISSUE TITLE
Ensure EntityStore is not being close prematurely

### ISSUE THREAD

**Issue by kerbymart** [divroll/datafactory#15]
The error message "Attempt to read closed log" suggests that there is an attempt to read from a log file that has already been closed. This can happen if the database connection was closed prematurely or if there is a concurrency issue where multiple threads are trying to access the database simultaneously.  

In the context of JetBrains Xodus, this error can occur when performing operations on the EntityStore after it has been closed.  Ensure that the `EntityStore` is not being closed prematurely. Also, make sure that all database operations are properly synchronized if they are being accessed from multiple threads. Identify where and why the EntityStore is being closed.

```
[main] INFO com.divroll.datafactory.conditions.PropertyNearbyConditionClientPerfTest - Time to complete query (ms): 141
[main] INFO jetbrains.exodus.env.EnvironmentImpl - Environment[/tmp/test/b38100ad-62d7-4e24-8a84-c0d47bf0ddf9] is active: 1 transaction(s) not finished
[EntityStoreSharedAsyncProcessor0] ERROR jetbrains.exodus.entitystore.EntityStoreSharedAsyncProcessor - Attempt to read closed log
java.lang.IllegalStateException: Attempt to read closed log
	at jetbrains.exodus.log.DataCorruptionException.checkLogIsClosing(DataCorruptionException.java:38)
	at jetbrains.exodus.log.BlockNotFoundException.raise(BlockNotFoundException.java:27)
	at jetbrains.exodus.log.BlockNotFoundException.raise(BlockNotFoundException.java:32)
	at jetbrains.exodus.log.Log.readBytes(Log.kt:782)
```

**Comment by kerbymart** [comment]
It seems it is related to the releasing of the database at:

```
@AfterClass
public static void afterAll() {
    dataFactory.release();
}
```
